language: node_js

node_js:
  - "6"

env:
  matrix:
  - TEST_TYPE=test
  - TEST_TYPE=lint
  - TEST_TYPE=flow
  - TEST_TYPE=build

install:
  - npm i

script:
  - |
    if [ "$TEST_TYPE" = test ]; then
      npm run test
    elif [ "$TEST_TYPE" = build ]; then
      npm run build
    elif [ "$TEST_TYPE" = lint ]; then
      npm run lint
    elif [ "$TEST_TYPE" = flow ]; then
      npm run flow
    fi

after_success:
  - |
    echo $TRAVIS_TAG
    echo $TEST_TYPE
  - |
    if [ "$TEST_TYPE" = test ]; then
      npm run coveralls
    fi
  - |
    if  [ "$TRAVIS_TAG" != "" ] && [ "$TEST_TYPE" == "build" ]; then
      cat ./packages/meta/package.json | sed s/0.0.0/$(git describe --tag)/g  > ./packages/meta/package.json
      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      lerna publish --skip-git --repo-version=$(git describe --tag) --yes --force-publish=*
    else
      echo "Skipping build because: TRAVIS_TAG=$TRAVIS_TAG TEST_TYPE=$TEST_TYPE"
    fi
