language: node_js

node_js:
  - "6"

env:
  matrix:
  - TEST_TYPE=test
  - TEST_TYPE=lint
  - TEST_TYPE=flow
  - TEST_TYPE=build
  - TEST_TYPE=docs

install:
  - npm i -g yarn rimraf
  - yarn install

script:
  - |
    if [ "$TEST_TYPE" = test ]; then
      npm run test
    elif [ "$TEST_TYPE" = build ]; then
      npm run build:lib
    elif [ "$TEST_TYPE" = lint ]; then
      npm run lint
    elif [ "$TEST_TYPE" = flow ]; then
      npm run flow
    elif [ "$TEST_TYPE" = docs ]; then
      npm run docs
    fi

after_success:
  - |
    if [ "$TEST_TYPE" = test ]; then
      npm run coveralls
    fi

before_deploy:
  - npm run publish -- --skip-git --npm-tag=$(git describe --tag) --skip-npm
  - npm run build

deploy:
  provider: npm
  api_key: "$NPM_TOKEN"
  email: "$NPM_EMAIL"
  skip_cleanup: true
  on:
    tags: true
    condition: $TEST_TYPE = build
