language: node_js

node_js:
  - "6"

# before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3
#  - "npm start &"
#  - sleep 3

cache:
    yarn: true
    directories:
        - node_modules

env:
  matrix:
  - TEST_TYPE=test
  - TEST_TYPE=lint
  - TEST_TYPE=flow
  - TEST_TYPE=build

script:
  - |
    if [ "$TEST_TYPE" = test ]; then
      npm run test:unit:coverage
    elif [ "$TEST_TYPE" = build ]; then
      npm run build
    elif [ "$TEST_TYPE" = lint ]; then
      npm run lint
    elif [ "$TEST_TYPE" = flow ]; then
      npm run flow
    fi

after_success:
  - |
    if [ "$TEST_TYPE" = test ]; then
      npm run coveralls
    fi

before_deploy:
  - npm version --no-git-tag-version $(git describe --tag)
  - npm run build

deploy:
  provider: npm
  api_key: "$NPM_TOKEN"
  email: "$NPM_EMAIL"
  skip_cleanup: true
  on:
    tags: true
    condition: $TEST_TYPE = build
