language: node_js

node_js:
  - "6"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash

install:
  - yarn

script:
  - npm run lint
  - npm run flow
  - npm run test
  - npm run build:lib

after_success:
  - npm run coveralls

deploy:
  provider: script
  skip_cleanup: true
  script: ./travis-deploy.sh
  on:
    tags: true
