language: node_js

node_js:
  - 0.12.7

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
    directories:
        - node_modules

script:
  - gulp lint
  - npm test

addons:
  code_climate:
    repo_token: aba9a7c425743c514e33ffee7629e71f7efee72cbd98c8be6e302c85e780658f

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
