language: node_js

node_js:
  - "6"

env:
  matrix:
  - TEST_TYPE=test
  - TEST_TYPE=lint
  - TEST_TYPE=flow
  - TEST_TYPE=build

install:
  - npm i -g yarn
  - yarn install
  - npm run bootstrap

script:
  - |
    if [ "$TEST_TYPE" = test ]; then
      npm run test
    elif [ "$TEST_TYPE" = build ]; then
      npm run build
    elif [ "$TEST_TYPE" = lint ]; then
      npm run lint
    elif [ "$TEST_TYPE" = flow ]; then
      npm run flow
    fi

after_success:
  - |
    if [ "$TEST_TYPE" = test ]; then
      npm run coveralls
    fi

before_deploy:
  - npm version --no-git-tag-version $(git describe --tag)
  - npm run build

deploy:
  provider: npm
  api_key: "$NPM_TOKEN"
  email: "$NPM_EMAIL"
  skip_cleanup: true
  on:
    tags: true
    condition: $TEST_TYPE = build
