language: node_js

node_js:
  - "6"

install:
  - yarn

script:
  - yarn run lint
  - yarn run flow
  - yarn run test
  - yarn run build:lib

after_success:
  - yarn run coveralls

deploy:
  provider: script
  skip_cleanup: true
  script: ./travis-deploy.sh
  on:
    tags: true
