language: node_js

node_js:
  - "6"

# before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3
#  - "npm start &"
#  - sleep 3

cache:
    directories:
        - node_modules

script:
  - npm run lint
  - npm run test:unit
  - npm run build

after_success:
  - codeclimate-test-reporter < coverage/lcov.info

before_deploy:
  - npm run clean
  - npm run build

deploy:
  provider: npm
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
